spring:
  application:
    name: pubsub-test
  cloud:
    gcp:
      project-id: poc-arquitetura
      credentials:
        location: classpath:auth.json

server:
  port: 9090

logging:
  level:
    org:
      springframework:
        web: INFO